### PR TITLE
Add protection for Chicken Bone's Wireless Redstone

### PR DESCRIPTION
**Pull request by Polyana-Fontes**

### CODE REVIEW

**Comment by krwminer** [comment]
You might want to look at expanding the range a bit. The problem with TRACKED entities is that we only check them every 20 ticks. So range should be: (area of effect + X) where X is used to account for the speed at which the entity may be traveling.

**Comment by Polyana-Fontes** [comment]
I'm wondering if EntityREP can be IMPACT instead of TRACKED now, I made this json before IMPACT was an idea

**Comment by krwminer** [comment]
I was thinking IMPACT at first then read a little bit about this thing. It sounds like it can be used like a hand grenade with a "fuse" rather than always exploding on impact. You need to test and make sure that is not the case. If it only explodes on impact, then IMPACT is by far the best choice. If not, you will have to play with it a bit and come up with some good numbers.

**Comment by Polyana-Fontes** [comment]
From what I see it exploded only on impact, but I'm going to do a proper test soon

**Pull request closed without merging**
